function Gravity = f_5dof_Gravity(in1,L,m_c,m_L,g)
%F_5DOF_GRAVITY
%    GRAVITY = F_5DOF_GRAVITY(IN1,L,M_C,M_L,G)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    16-Feb-2015 14:55:53

phi_L = in1(4,:);
theta_L = in1(5,:);
Gravity = [0.0;0.0;-g.*(m_L+m_c);L.*g.*m_L.*cos(theta_L).*sin(phi_L);L.*g.*m_L.*cos(phi_L).*sin(theta_L)];
